apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../base
  - namespace.yaml

namePrefix: staging-

commonLabels:
  environment: staging

images:
  - name: aden-hive
    newName: gcr.io/acho-alpha-project/aden-hive
    newTag: latest

patches:
  - path: patches/deployment.yaml
