apiVersion: apps/v1
kind: Deployment
metadata:
  name: aden-hive
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: aden-hive
          env:
            - name: NODE_ENV
              value: staging
          envFrom:
            - configMapRef:
                name: aden-api-server-config
            - secretRef:
                name: aden-api-server-secrets
            - secretRef:
                name: database-secrets
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
